package com.myspace.gestioncredito.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Credito implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Valor del Credito")
	private java.lang.Integer valorCredito;
	@org.kie.api.definition.type.Label(value = "Tiempo de Amortizacion")
	private java.lang.Integer tiempoAmortiza;
	@org.kie.api.definition.type.Label(value = "Salario de la Persona")
	private java.lang.Integer salarioPersona;
	@org.kie.api.definition.type.Label(value = "Gastos de la Persona")
	private java.lang.Integer gastosPersona;

	public Credito() {
	}

	public java.lang.Integer getValorCredito() {
		return this.valorCredito;
	}

	public void setValorCredito(java.lang.Integer valorCredito) {
		this.valorCredito = valorCredito;
	}

	public java.lang.Integer getTiempoAmortiza() {
		return this.tiempoAmortiza;
	}

	public void setTiempoAmortiza(java.lang.Integer tiempoAmortiza) {
		this.tiempoAmortiza = tiempoAmortiza;
	}

	public java.lang.Integer getSalarioPersona() {
		return this.salarioPersona;
	}

	public void setSalarioPersona(java.lang.Integer salarioPersona) {
		this.salarioPersona = salarioPersona;
	}

	public java.lang.Integer getGastosPersona() {
		return this.gastosPersona;
	}

	public void setGastosPersona(java.lang.Integer gastosPersona) {
		this.gastosPersona = gastosPersona;
	}

	public Credito(java.lang.Integer valorCredito,
			java.lang.Integer tiempoAmortiza, java.lang.Integer salarioPersona,
			java.lang.Integer gastosPersona) {
		this.valorCredito = valorCredito;
		this.tiempoAmortiza = tiempoAmortiza;
		this.salarioPersona = salarioPersona;
		this.gastosPersona = gastosPersona;
	}

}