package com.myspace.gestioncredito.model.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PersonaBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Primer Nombre")
	private java.lang.String primerNombre;
	@org.kie.api.definition.type.Label("Segundo Nombre")
	private java.lang.String segundoNombre;
	@org.kie.api.definition.type.Label("Primer Apellido")
	private java.lang.String primerApellido;
	@org.kie.api.definition.type.Label("Segundo Apellido")
	private java.lang.String segundoApellido;
	@org.kie.api.definition.type.Label("Tipo Documento")
	private java.lang.String tipoDocumento;
	@org.kie.api.definition.type.Label("Numero Docuemento")
	private java.lang.Integer numeroDocuemento;
	@org.kie.api.definition.type.Label("Fecha Nacimiento")
	private java.util.Date fechaNacimiento;

	@org.kie.api.definition.type.Label("Aprobado")
	private String aprobado;

	public PersonaBO() {
	}

	public java.lang.String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(java.lang.String primerNombre) {
		this.primerNombre = primerNombre;
	}

	public java.lang.String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(java.lang.String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	public java.lang.String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(java.lang.String primerApellido) {
		this.primerApellido = primerApellido;
	}

	public java.lang.String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(java.lang.String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	public java.lang.String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(java.lang.String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public java.lang.Integer getNumeroDocuemento() {
		return this.numeroDocuemento;
	}

	public void setNumeroDocuemento(java.lang.Integer numeroDocuemento) {
		this.numeroDocuemento = numeroDocuemento;
	}

	public java.util.Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(java.util.Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public java.lang.String getAprobado() {
		return this.aprobado;
	}

	public void setAprobado(java.lang.String aprobado) {
		this.aprobado = aprobado;
	}

	public PersonaBO(java.lang.String primerNombre,
			java.lang.String segundoNombre, java.lang.String primerApellido,
			java.lang.String segundoApellido, java.lang.String tipoDocumento,
			java.lang.Integer numeroDocuemento, java.util.Date fechaNacimiento,
			java.lang.String aprobado) {
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.tipoDocumento = tipoDocumento;
		this.numeroDocuemento = numeroDocuemento;
		this.fechaNacimiento = fechaNacimiento;
		this.aprobado = aprobado;
	}

}