package com.myspace.gestioncredito.interfaz;

import com.myspace.gestioncredito.model.dto.Credito;

/**
 * This class was automatically generated by the data modeler tool.
 */

public interface IServicioCalculoCredito{

        public Integer cacularcredito(Credito credito);

}