package com.myspace.gestioncredito.implementacion;

import com.myspace.gestioncredito.interfaz.IServicioCalculoCredito;
import com.myspace.gestioncredito.model.dto.Credito;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServicioCalculoCredito implements IServicioCalculoCredito {
	//Integer endeudamiento;
	@Override
	public Integer cacularcredito(Credito credito) {
	    Integer Salario = credito.getSalarioPersona();
	    Integer Gastos = credito.getGastosPersona();
	    Integer Amortizacion = credito.getTiempoAmortiza();
	    
		Integer endeudamiento = (int)(0.25*(Salario-Gastos))/Amortizacion;
		
		return endeudamiento;
	}
}